version: '3'
networks:
  main:
volumes:
  database:
services:
  airy:
    build: ./airy/
    volumes:
      - ./airy/docker/local_config.py:/opt/kankin-airy/airy/local_config.py
    networks:
      - main
  yuui:
    build: ./yuui/
    restart: always
    ports:
      - 8080:8080
    environment:
      NGINX_HOST: "kankin2.nyiyui.ca"
      NGINX_PORT: "8080"
    networks:
      - main
  redis:
    image: redis:latest
    restart: always
    networks:
      - main
  database:
    image: mariadb:latest
    restart: always
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: kankin_airy_db
      MYSQL_USER: kankin_airy_user
      MYSQL_PASSWORD: very_secure_password
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    networks:
      - main
