version: '3'
networks:
  main:
volumes:
  database:
services:
  airy:
    build: ./airy/
    volumes:
      - ./airy/docker/local_config.py:/opt/kyii-airy/airy/local_config.py
    networks:
      - main
  yuui:
    build: ./yuui/
    ports:
      - 3000:3000
    environment:
      #HOST: "0.0.0.0"
      #PORT: "3000"
      NGINX_HOST: "yuui.kyii.nyiyui.ca"
      NGINX_PORT: "3000"
  nginx:
    build: ./nginx/
    restart: always
    ports:
      - 8080:8080
    environment:
      NGINX_HOST: "airy.kyii.nyiyui.ca"
      NGINX_PORT: "8080"
    networks:
      - main
  redis:
    image: redis:latest
    restart: always
    networks:
      - main
  database:
    image: mariadb:latest
    restart: always
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: kyii_airy_db
      MYSQL_USER: kyii_airy_user
      MYSQL_PASSWORD: very_secure_password
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    networks:
      - main
