"""replace primary group with email directly

Revision ID: 01e6386e167b
Revises: c569911847cf
Create Date: 2022-11-12 04:34:13.055737

"""
from alembic import op
import sqlalchemy_utils
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01e6386e167b'
down_revision = 'c569911847cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_id', sa.String(length=32), nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'email', ['email_id'], ['id'])
    op.drop_column('user', 'primary_group_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('primary_group_id', sa.VARCHAR(length=32), nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'group', ['primary_group_id'], ['id'])
    op.drop_column('user', 'email_id')
    # ### end Alembic commands ###
