"""logs2

Revision ID: 14c3f0cfbd44
Revises: 7193e8ba1f9c
Create Date: 2022-07-10 14:26:47.128538

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = "14c3f0cfbd44"
down_revision = "7193e8ba1f9c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("log_entry", sa.Column("sid2", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("log_entry", "sid2")
    # ### end Alembic commands ###
