"""init3

Revision ID: 835615025f59
Revises: 84fb61f00c10
Create Date: 2022-05-20 16:03:05.088360

"""
from alembic import op
import sqlalchemy_utils
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835615025f59'
down_revision = '84fb61f00c10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_login', sa.Column('last', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_login', 'last')
    # ### end Alembic commands ###
