"""init2

Revision ID: 84fb61f00c10
Revises: b0e8385c7cd3
Create Date: 2022-05-20 14:09:31.977176

"""
from alembic import op
import sqlalchemy_utils
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84fb61f00c10'
down_revision = 'b0e8385c7cd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('af', sa.Column('state', sqlalchemy_utils.types.json.JSONType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('af', 'state')
    # ### end Alembic commands ###
