"""add ap_reqs level

Revision ID: c569911847cf
Revises: d69a3ab80d73
Create Date: 2022-11-06 00:07:33.592170

"""
from alembic import op
import sqlalchemy_utils
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c569911847cf"
down_revision = "d69a3ab80d73"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ap_reqs", sa.Column("level", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ap_reqs", "level")
    # ### end Alembic commands ###
