"""init4

Revision ID: ed98934eb10d
Revises: 835615025f59
Create Date: 2022-05-20 21:14:21.291160

"""
from alembic import op
import sqlalchemy_utils
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed98934eb10d'
down_revision = '835615025f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_login', sa.Column('reason_end', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_login', 'reason_end')
    # ### end Alembic commands ###
