# Generated by Django 4.0.4 on 2022-05-03 15:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub',
            field=models.CharField(default=core.models.gen_sub, max_length=256),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
