import i18n from 'sveltekit-i18n';

// generated by nyiyui.ca/kyii/yuui/src/lib/i18n/gen on 2022-05-17T16:40:03-04:00

/** @type {import('sveltekit-i18n').Config} */
export const config = {
	translations: {
		'en-CA': {
			lang: {
				'en-CA': 'Canadian English',
				'ja-JP': 'カナダ英語'
			}
		},
		'ja-JP': {
			lang: {
				'en-CA': 'Japanese',
				'ja-JP': '日本語'
			}
		}
	},
	loaders: [
		{
			locale: 'en-CA',
			key: 'common',

			loader: async () => (await import('./en-CA/common.json')).default
		},

		{
			locale: 'en-CA',
			key: 'about',
			routes: ['/about'],
			loader: async () => (await import('./en-CA/about.json')).default
		},

		{
			locale: 'ja-JP',
			key: 'common',

			loader: async () => (await import('./ja-JP/common.json')).default
		},

		{
			locale: 'ja-JP',
			key: 'about',
			routes: ['/about'],
			loader: async () => (await import('./ja-JP/about.json')).default
		}
	]
};

export const { t, locale, locales, loading, loadTranslations } = new i18n(config);

loading.subscribe(($loading) => $loading && console.log('Loading translations...'));
