name: Lint
on:
  push:

# TODO: line airy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Yuui Dependencies
      working-directory: ./yuui
      run: |
        npm i --include=dev
    - name: Yuui Lint
      working-directory: ./yuui
      run: |
        npm run lint
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Airy Dependencies
      working-directory: ./airy
      run: |
        python -m pip install pipenv
        pipenv install --dev --skip-lock
    - name: Airy Flake8
      working-directory: ./airy
      run: pipenv run flake8
    - name: Airy Black
      working-directory: ./airy
      run: pipenv run black --check
