name: Lint
on:
  push:

jobs:
  airy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Dependencies
      working-directory: ./airy
      run: |
        python -m pip install poetry
        poetry install
    - name: Black
      working-directory: ./airy
      run: poetry run black --check .
    - name: Flake8
      working-directory: ./airy
      run: poetry run flake8
    - name: mypy
      working-directory: ./airy
      run: poetry run mypy --strict $(git ls-files '*.py') || echo 'failed but wtv'
